### ISSUE TITLE
The task list is empty

### ISSUE THREAD

**Issue by BearOutThere** [victor-homyakov/jetbrains-targetprocess-assigned-entities#9]
Hello,
just installed your plugin, setup Targetprocess server and login, tested the connection, and clicked to start a new task but there's nothing in the list.  I expected to see user stories and tasks from TP presented in the list to work on.
Is there another configuration somewhere?  The documentation is rather scarce.
Any help would be greatly appreciated.

**Comment by BearOutThere** [comment]
I tried the other TP plugin and it retrieves some of the TP items but not all and doesn't filter out done items nor the ones assigned to others.  I really hope that we can make your plugin work.
Thanks in advance.

**Comment by victor-homyakov** [comment]
Do I properly understand that you want to see Tasks, not User Stories and Bugs? The list of retrieved entities is hard-coded right now and limited to User Stories and Bugs only.

I've taken the entities from my typical workflow, but this is discussable.

**Comment by victor-homyakov** [comment]
Let me explain a bit more. Task and Context management in IDEA is way more complex than just plain list of current tasks:
- each IDEA's task has associated list of opened files, VCS (e.g. Git) branch, and named set of changed files
- when you starting a task, IDEA proposes to create new VCS branch, and new change set
- when you switching from this task, IDEA also switches to default VCS branch and removes change set if it is empty

Therefore I think IDEA's tasks correspond to User Stories and Bugs in Targetprocess - the units of work which are typically done in separate branches, with separate files. Tasks in Targetprocess are more subtle units of work and don't require their own VCS branch, change set, pull request etc.

**Comment by BearOutThere** [comment]
Hey Victor, 
firstly thank you very much for sharing your work with everybody.  It is much appreciated.
Our initial problem was that nothing was being pulled from TargetProcess.  The server was setup but no user stories, no bugs appeared in the plugins popup.  When i wrote "task" i used IDEA's terminology not TP.

As far as the usage of tasks vs user stories vs bugs it varies for us.  It is common for a user story to have both backend and front end components.  In order to keep all of the work in the user story we create TP tasks for each and assign them to different developers who work on different code bases.  So in that case we would need a separate VCS branch and commit for each TP task.  

In the past i have used Mylyn with Eclipse and Subversion.  It worked very well, and even pushed Eclipse context (set of all open files, etc.) to the repository so other developers could open that context if they needed to work on the same task.  This is the kind of productivity enhancements that we would very much like to have.  
Please let me know if you need any additional information.

All the best.

**Comment by victor-homyakov** [comment]
Hi Kiril!

There is a "Test" button in the settings - could you please test if plugin connects with Targetprocess successfully as on attached screenshot?

![settings - tasks](https://cloud.githubusercontent.com/assets/121449/18305269/710234c0-74ef-11e6-9616-96f9627c555a.png)

**Comment by BearOutThere** [comment]
I tested from the beginning and always got "Connection successful"

**Comment by victor-homyakov** [comment]
Could you check if the file `idea.log` contains lines like these

```
2016-09-01 17:39:37,760 [14993458]   INFO - signed.TargetprocessRepository - Get issues http://***.tpondemand.com/api/v2/assignable?...
2016-09-01 17:39:39,440 [14995138]   INFO - signed.TargetprocessRepository - Received 5 assignable items 
2016-09-01 17:39:39,440 [14995138]   INFO - lij.tasks.impl.TaskManagerImpl - Total 1680 ms to download 5 issues from 'http://***.tpondemand.com' (pattern 'null') 
```

`idea.log` location:
on Windows it is located in your user profile folder (`%USERPROFILE%`) in `\.<Your IDE name>\system\log` folder.

**Comment by BearOutThere** [comment]
2016-09-07 18:41:48,324 [1206553]   INFO - signed.TargetprocessRepository - Get issues https://uncircled.tpondemand.com/api/v2/assignable?select=%7Bid%2Cname%2Cdescription%2CentityType%3AentityType.name%7D&where=%28assignedUser.where%28it.login%3D%3D%27kiril%40uncircled.asia%27%29.Count%3E0%29and%28entityType.name%3D%3D%27Bug%27+or+entityType.name%3D%3D%27UserStory%27%29and%28entityState.isFinal%3D%3Dfalse%29&orderBy=id+desc 
2016-09-07 18:41:49,444 [1207673]   INFO - signed.TargetprocessRepository - Received 0 assignable items 
2016-09-07 18:41:49,444 [1207673]   INFO - lij.tasks.impl.TaskManagerImpl - Total 1120 ms to download 0 issues from 'https://uncircled.tpondemand.com' (pattern 'null')

**Comment by victor-homyakov** [comment]
Could you go to your Targetprocess URL in browser, log in, then paste that request into the address line, press Enter and look for a response

```
https://uncircled.tpondemand.com/api/v2/assignable?select={id,name,description,entityType:entityType.name}&where=(assignedUser.where(it.login=='kiril@uncircled.asia').Count>0)and(entityType.name=='Bug'+or+entityType.name=='UserStory')and(entityState.isFinal==false)&orderBy=id+desc
```

TP server should return JSON with assigned user stories and bugs (you don't need to post it here), just verify that it doesn't respond with `{"items":[]}` or `Some errors occurred`.

**Comment by victor-homyakov** [comment]
One more question: check please that `Username` field in IDEA's settings

![settings - username](https://cloud.githubusercontent.com/assets/121449/18311768/cb8af610-750e-11e6-8c66-a9e33b18d5fe.png)

 is the same as `Login` field in your Targetprocess's profile (Targetprocess - Your avatar in the top right corner - My profile)

![user settings](https://cloud.githubusercontent.com/assets/121449/18311568/a90915e6-750d-11e6-9235-fbed713aff9d.png)

**Comment by BearOutThere** [comment]
yes,  double checked that as well.  it appears to be working since i get "Connection successful"

**Comment by BearOutThere** [comment]
i get {"items":[]} with the url above

**Comment by victor-homyakov** [comment]
Well, looks like everything is working fine. Maybe you just don't have any assigned entities? In order to appear in IDEA, User Stories and Bugs in Targetprocess should be already assigned to you.

**Comment by BearOutThere** [comment]
so I deleted the login in TP and re-entered it and saved.  and it works now.  so i guess there was some kind of strange character in there that was failing the match
it works now.  thanks a lot for the support.

any way to include Tasks as well as User Stories and Bugs?

**Comment by victor-homyakov** [comment]
Maybe yes. I'll think a bit about it.

**Comment by BearOutThere** [comment]
Great thanks.  What about pushing the context to the repository with the task/context commit so other developers can open it when working on the same task?

**Comment by BearOutThere** [comment]
Actually,  the context would need to be saved to TargetProcess, not VCS to make it workable.  Perhaps TP custom fields could be used.  I'm just not sure how WebStorm serializes contexts.

**Comment by victor-homyakov** [comment]
The only thing I know is that WebStorm stores parts of context in `.idea\workspace.xml` file (section `<component name="TaskManager">`).

Few important points are not clear to me:
- how to work with this context in IDEA
- at what points in time should it be exported
- how to solve conflicts if it will be stored as some shared resource (imagine that two assigned developers work on the same task simultaneously - both plugins will try to write their different contexts to the same place)

So if you have any experience with that - you are welcome!

**Comment by BearOutThere** [comment]
Here are my thoughts on this:
- how to work with this context in IDEA
  i don't think there needs to be any changes within the IDE in terms of how contexts work
- at what points in time should it be exported
  the most logical point is the commit to VCS
- how to solve conflicts if it will be stored as some shared resource (imagine that two assigned developers work on the same task simultaneously - both plugins will try to write their different contexts to the same place)
  this is fine.  the latest commit will override the context in TP.  It is very rare 2 people will be working on exactly the same task.  This is the scenario that we use TP tasks for.  So even if 2 people are working on the same user story they will be working on different tasks, so no danger of the override.  But even if that happens the cost of opening another file is very low.  So there's no need of any complex concurrency management.  A single field on a TP entitiy (user story, bug, or task) will be more than sufficient.

I don't know Java so won't be able to take this on myself.  But based on my research there's nothing that provides this Mylyn-like functionality in JetBrains IDEs right now, but a lot of people asking for it.
